name: Angular CI

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.20.1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.1'
          
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        
      - name: Clear directory before deployment.
        uses: appleboy/ssh-action@master
        with:
         host: toefl-test.uz
         username: toefltes
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: rm -rf /home/toefltes/domains/toefl-test.uz/public_html/*
         
      - name: Deploy 
        uses: appleboy/scp-action@master
        with:
          host: toefl-test.uz
          username: toefltes
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/toefl-uzbek-angular/*"
          target: "/home/toefltes/domains/toefl-test.uz/public_html/"
          
      - name: Move files
        uses: appleboy/ssh-action@master
        with:
         host: toefl-test.uz
         username: toefltes
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: |
          cd /home/toefltes/domains/toefl-test.uz/public_html/
          mv dist/toefl-uzbek-angular/* .
#          find . -mindepth 1 ! \( -name 'dist' -o -name '.htaccess' \) -exec rm -rf {} +
          
