name: Deploy to SSH Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: toefl-test.uz
          username: toefltes
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/toefltes/domains/toefl-test.uz/public_html/
            rm -rf *
            exit
          script_stop: true

      - name: Copy files to Server
        uses: appleboy/scp-action@master
        with:
          host: toefl-test.uz
          username: toefltes
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/toefl-uzbek-angular/*"
          target: "/home/toefltes/domains/toefl-test.uz/public_html/"


#name: Angular CI
#
#on:
#  push:
#    branches: [develop]
#
#jobs:
#  build-and-deploy:
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [16.20.1]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v2
#        with:
#          node-version: '16.20.1'
#      - name: Install Dependencies
#        run: npm install
#      - name: Build
#        run: npm run build
#      - name: Deploy copy file via ssh password
#        uses: appleboy/scp-action@master
#        with:
#          host: toefl-test.uz
#          username: toefltes
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          source: "dist/toefl-uzbek-angular/"
#          target: "/home/toefltes/domains/toefl-test.uz/public_html/"
