name: Deploy to SSH Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: toefl-test.uz
          username: toefltes
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/toefltes/domains/toefl-test.uz/public_html/
            rm -rf *
            exit
          script_stop: true

      - name: Copy files to Server
        uses: appleboy/scp-action@master
        with:
          host: toefl-test.uz
          username: toefltes
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/toefl-uzbek-angular/*"
          target: "/home/toefltes/domains/toefl-test.uz/public_html/"
